// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: authors.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (id, name, username)
VALUES ($1, $2, $3)
RETURNING id, name, username, created_at, updated_at
`

type CreateAuthorParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Username string    `json:"username"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, arg.ID, arg.Name, arg.Username)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAuthor = `-- name: DeleteAuthor :one
DELETE FROM authors
WHERE username = $1
RETURNING username
`

func (q *Queries) DeleteAuthor(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, deleteAuthor, username)
	err := row.Scan(&username)
	return username, err
}

const getAuthors = `-- name: GetAuthors :many
SELECT id, name, username, created_at, updated_at FROM authors
`

func (q *Queries) GetAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, getAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Author{}
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
