// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateState(ctx context.Context, arg CreateStateParams) (State, error)
	DeleteAuthor(ctx context.Context, username string) (string, error)
	GetAuthors(ctx context.Context) ([]Author, error)
	GetProjects(ctx context.Context) ([]Project, error)
	GetProjectsByAuthor(ctx context.Context, author uuid.UUID) ([]Project, error)
	GetStatesByProject(ctx context.Context, project uuid.UUID) ([]State, error)
}

var _ Querier = (*Queries)(nil)
